services:
  db:
    image: mysql:5.7
    # container_name: db-my-login-app
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3320:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: api-my-login-app
    environment:
      JWT_SECRET: ${JWT_SECRET}
      # DB_HOST: ${DB_HOST}
      # DB_PORT: ${DB_PORT}
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3010:3000"
    depends_on:
      - db
    networks:
      - net

volumes:
  db-data:

networks:
  net:
    driver: bridge
